steps:
  - name: gcr.io/k8s-skaffold/pack
    entrypoint: pack
    env:
      - GOOGLE_ENTRYPOINT=$_ENTRYPOINT
    args:
      - build
      - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - '--builder=gcr.io/buildpacks/builder:universal_builder_20260202_RC02'
      - '--network=cloudbuild'
      - '--publish'
      - '--path=.'
      - '--env=GOOGLE_ENTRYPOINT'
    id: Buildpack

  - name: gcr.io/cloud-builders/docker
    args:
      - pull
      - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Pull

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - >-
        --image=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - '--region=$_DEPLOY_REGION'
      - >-
        --service-account=jisong-cloud-run@jisong-cloud-492111.iam.gserviceaccount.com
      - '--update-env-vars=GCS_BUCKET_NAME=$_GCS_BUCKET_NAME'
      - '--update-secrets=ADMIN_PASSWORD=admin-password:1'
      - '--quiet'
    id: Deploy

images:
  - >-
    $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _PLATFORM: managed
  _SERVICE_NAME: jisong-cloud-tokyo
  _ENTRYPOINT: >-
    streamlit run jisong_cloud.py --server.address 0.0.0.0 --server.port 8080
  _TRIGGER_ID: 5aafb059-da56-422d-a34e-e10bbb709fa7
  _DEPLOY_REGION: asia-northeast1
  _AR_HOSTNAME: asia-northeast1-docker.pkg.dev
  _AR_REPOSITORY: cloud-run-source-deploy
  _AR_PROJECT_ID: jisong-cloud-492111
  _GCS_BUCKET_NAME: jisong-cloud-storage

tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - jisong-cloud-tokyo